name: Jira PR Check
on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize
jobs:
  enforce-issue:
    runs-on: ubuntu-latest
    name: JIRA Association
    steps:
      - uses: actions/checkout@v3
      - name: Check for JIRA ISSUE
        id: check
        uses: ./
        with:
          ignore-author: dependabot[bot]
          jira-project: "SRENEW"
          jira-host: ${{ secrets.JIRA_HOST }}
